MissingCore/Music

- src/api/playlists/[id].ts
- src/app/(app)/(current)/album/[id].tsx
- src/app/(app)/(home)/artist.tsx
- src/db/utils/formatters.ts
- src/features/modal/modals/TrackModal.tsx
While thinking of potentially redesigning the `album` schema such that we no longer need an `id` field as we can just rely on `${artist name}/${album name}` as the key, I wondered if having either back or forward slashes as part of a Playlist or Artist name would break anything. They in fact, led to an "invalid route" error being thrown.
The solution ended up being running `encodeURIComponent()` on the parameter that gets inserted into the href of an Artist or Playlist link.
Testing whether we can create a playlist with `\` or `/` and navigate to it. In addition, see if we can add & remove tracks from this playlist.
> fix: Error throw for `\` or `/` in playlist name

- src/app/(app)/(current)/_layout.tsx
- src/app/(app)/(current)/album/[id].tsx
- src/app/(app)/(current)/playlist/[id].tsx
- src/app/(app)/_layout.tsx
- src/app/_layout.tsx
- src/components/navigation/header.tsx
This aims to fix the issue with tap target size in the header warned by the Play Console (ie: they should be at least `48px` in size). In addition, we want to match the design changes seen when we changed the `<AnimatedHeader />` implementation:
- Tap target size of the back button is `48px`.
- Padding values on sides where we have a button is `4px`.
On the screens that uses the default header provided by React Navigation, we added `header: CustomHeader`, where `CustomHeader` is the custom header component that mimics the one used in `<AnimatedHeader />`.
For tap target size, we added the `p-3` class to the pressables placed in the `headerRight` option, which adds `12px` around a `24px` icon, giving it a size of `48px`. We also added an opacity effect when pressed if they weren't present. …
> fix: Adjust header to match design in `<AnimatedHeader />`

- package.json
- pnpm-lock.yaml
- src/app/(app)/(current)/album/[id].tsx
- src/app/(app)/(current)/playlist/[id].tsx
- src/app/(app)/(home)/playlist.tsx
- src/app/(app)/_layout.tsx
- src/app/_layout.tsx
- src/app/setting/index.tsx
- src/app/setting/third-party/index.tsx
- src/assets/licenses.json
- src/assets/svgs/ArrowRight.tsx
- src/assets/svgs/EllipsisVertical.tsx
- src/components/form/action-button.tsx
- src/components/form/button.tsx
- src/components/form/checkbox-field.tsx
- src/components/icons.tsx
- src/components/media/screen-header.tsx
- src/components/navigation/animated-header.tsx
- src/components/navigation/back.tsx
- src/components/navigation/header.tsx
- src/components/navigation/nav-link.tsx
- src/components/ui/pressable.tsx
- src/features/modal/components/form-button.tsx
- src/features/modal/modals/playlist-delete.tsx
- src/features/modal/modals/playlist-name.tsx
- src/features/modal/modals/playlist.tsx
- src/features/modal/modals/track-to-playlist.tsx
- src/features/modal/modals/track.tsx
- src/features/modal/modals/upcoming-track/index.tsx
- src/features/playback/components/media-controls.tsx
When we changed the UI on the pages in the `/setting` route, we changed the styling of `text-title` — which was previously `32px`, now `36px`. This PR mainly aims to adjust any use of `text-title`.
In addition, we decided to improve the tap size of some components (due to Google recommending tap targets being at least `48px` in size). We've also utilized `android_ripple` on `<Pressable />` to add some micro animations.
We've also downgraded `@gorhom/bottom-sheet@5.0.0-alpha.10` to `@gorhom/bottom-sheet@5.0.0-alpha.9` due to a regression with the "Keyboard Handling" feature where dismissing the keyboard keeps the modal in the same position, instead of moving it back to the bottom of the screen.
I also found some unintended behavior for removing a track from the queue — we could previously …
> chore: Micro-animations & UI/UX Adjustments & Fixes

- src/components/ui/progress-bar.tsx
Closes #25.
There was a report of a very glitchy "Storage & Backup" screen, in which it was an epilepsy nightmare. I was a bit confused as I wasn't having this issue on my Nothing Phone 2a & OnePlus 6 on the version released in the Play Store `v1.0.0-rc.8`.
I opened up a dev instance of the app (via `pnpm android`) and went to the "Insights" page (since we broke up the "Storage & Backup" page) and saw this issue.
I initially thought it was due to the user not having any images stored by the app, causing this weirdness to occur. Well, this wasn't the case.
I then started messing around with logging and saw that `onLayout` in `<ProgressBar />` was getting called repeatedly. After investigating and removing some classes, I narrowed down the cause to the `flex-1` class being applied to the …
> fix: Epilepsy on Insights (prev "Storage") page

- src/components/navigation/animated-header.tsx
- src/components/navigation/header.tsx
I usually do the dev testing on a OnePlus 6 to validate things work on older devices. However, during my fix of the epilepsy on the "Insights" (prev "Storage & Backup") screen, I noticed that the dynamic sizing we apply to the `<AnimatedHeader />` didn't work.
Checking `onLayout`, I noticed it was firing a lot - so I assumed the same problem occured as with #27, so I removed the `flex-1`. However, that wasn't a good solution as direct content (ie: `<FlashList />`) requires the parent to have `flex-1` for a better initial layout.
After a bit of experimenting, I narrowed down the problem to me conceptualizing the value from `useWindowDimensions()` in the wrong way - I though it also included the top status bar, but it doesn't.
- I'm kind of wondering why I didn't face this issue while …
> fix: Dynamic `<AnimatedHeader />` size

- src/app/setting/insights.tsx
- src/features/setting/api/_queryKeys.ts
- src/features/setting/api/insights.ts
- src/hooks/useSaveAudio/cleanUpImages.ts
Adding an indicator on whether all images have been saved can help narrow down whether an issue is due to a bug or due to images not all being saved.
We display this information in the "Insights" screen. We can take advantage of the `fetchedArt` field in the `Track` schema.
We've also broke up the logic for generating the widgets for better separation of concerns.
Check the "Insights" screen and see the new "widget" displays whether all images have been saved. If we stayed on that page while images are being saved, it should update once all images have been saved.
> chore: indicator if we've saved all tracks

- src/app/(app)/(current)/artist/[id].tsx
- src/db/schema.ts
- src/features/indexing/api/db-cleanup.ts
- src/features/indexing/api/index-audio.ts
An issue brought up by `trad0r.` in the Discord is that for albums with tracks from different artists, with the way we currently implemented things, we'll create different album instances for each artist, when the expected behavior is that they should all be combined.
The solution is to use a new field - `albumArtist`, which we implemented in `@missingcore/audio-metadata@1.3.0`, and use this instead of `artist` for creating albums.
Closes #26.
We had several things we needed to make sure is in working order:
- Update the `/artist/[id]` screen to handle the case where the artist has no tracks (ie: artist made just hold "collaboration albums").
- Make sure our cleanup logic for artists without tracks get changed based on the behavior change mentioned above (ie: take into consideration of …
> fix: Album "fracturizaiton"

- src/app/setting/insights.tsx
- src/components/navigation/animated-boot-splash.tsx
- src/components/navigation/animated-header.tsx
- src/components/ui/loading.tsx
- src/db/drizzle/0001_wooden_wallop.sql
- src/db/drizzle/meta/0001_snapshot.json
- src/db/drizzle/meta/_journal.json
- src/db/drizzle/migrations.js
- src/db/schema.ts
- src/db/utils/formatters.ts
- src/features/indexing/Config.ts
- src/features/indexing/api/index-audio.ts
- src/features/indexing/api/index-override/album-fracturization.ts
- src/features/indexing/api/index-override/index.ts
- src/features/modal/modals/track.tsx
- src/features/modal/modals/upcoming-track/index.tsx
- src/features/playback/components/mini-player.tsx
- src/features/setting/api/backup.ts
- src/features/setting/api/insights.ts
For the future folder feature & preparation for supporting decoding metadata for any audio file that Android supports, it would make sense to support tracks that don't have any tags.
- We'll fallback to the filename for the name of the track.
- We have no plans for parsing the filename to potentially get the artist name (yet).
- We'll still **enforce that we must have an artist or album artist tag for an album**.
Implementing this change requires a couple of steps:
1. **Create a database migration** as we're changing the type on a column. This ended up being a bit more difficult than expected; given that Drizzle ORM doesn't automatically generate the migration file for SQLite and documentation for creating migrations manually is a bit sparse (spent most of my time wondering why my …
> feat: Support tracks without tags

- src/api/file-nodes/[...id].ts
- src/api/file-nodes/_queryKeys.ts
- src/app/(app)/(home)/_layout.tsx
- src/app/(app)/(home)/folder/[...id].tsx
- src/app/(app)/(home)/folder/index.tsx
- src/assets/svgs/MaterialSymbol.tsx
- src/components/ui/container.tsx
- src/db/drizzle/0002_third_giant_man.sql
- src/db/drizzle/meta/0002_snapshot.json
- src/db/drizzle/meta/_journal.json
- src/db/drizzle/migrations.js
- src/db/schema.ts
- src/db/utils/sorting.ts
- src/features/indexing/Config.ts
- src/features/indexing/api/index-audio.ts
- src/features/indexing/api/index-override/index.ts
- src/features/indexing/api/library-scan.ts
- src/features/indexing/hooks/useIndexAudio.ts
- src/features/playback/api/actions.ts
- src/features/playback/api/recent.ts
- src/features/playback/types.ts
- src/features/playback/utils.ts
This was something requested by `Ghouless` on the [Nothing Forums](https://nothing.community/d/12384-music-open-source-offline-music-player/5) to relieve some potential issues with our current setup in regards to organization & searchability and should close #23.
Theoretically, everything in this PR should allow for folder structure and playing a track in some directory in the folder structure should only play the tracks directly in this directory.
When trying to implement the above, I realized that the core logic controlling the app is pretty messy and a bit all over the place. With that in mind, after improving file support in the app, I'll probably work on refactoring the logic and probably rewrite the playing logic, which might fix some of the other issues (ie: `#30`).
The overall …
> feat: View tracks in "Folder" structure

- .github/ISSUE_TEMPLATE/config.yml
- CHANGELOG.md
- README.md
- THIRD_PARTY.md
- android/gradle.properties
- package.json
- pnpm-lock.yaml
- scripts/licenseClarification.json
- src/assets/licenses.json
- src/features/indexing/Config.ts
- src/features/indexing/api/artwork-save.ts
- src/features/indexing/api/index-audio.ts
- src/features/indexing/api/index-override/album-fracturization.ts
With the `@missingcore/audio-metadata` package, performance wasn't the best and we had a limited scope  in what metadata & files we supported. With the shift to a native module through `@missingcore/react-native-metadata-retriever`, we can take advantage of the built-in metadata reader provided by Android and support more files & improve performance drastically.
With the switch of package, we also fix a previous problem that prevented the "tagless" feature support for working as expected as `@missingcore/audio-metadata` would throw an error if the ["magic number"](https://en.wikipedia.org/wiki/List_of_file_signatures) wasn't present. Now, with `@missingcore/react-native-metadata-retriever`, we just return the expected metadata object, but with all the fields set to `null`.
This should fix …
> perf: Improved track saving speed

- README.md
- THIRD_PARTY.md
- package.json
- pnpm-lock.yaml
- src/api/file-nodes/[...id].ts
- src/app/(app)/(home)/_layout.tsx
- src/app/(app)/(home)/folder/[...id].tsx
- src/app/(app)/(home)/folder/_layout.tsx
- src/app/(app)/(home)/folder/index.tsx
- src/assets/licenses.json
- src/components/ui/container.tsx
- src/db/schema.ts
- src/features/indexing/Config.ts
- src/features/indexing/api/index-audio.ts
- src/features/indexing/api/index-override/index.ts
- src/features/indexing/api/library-scan.ts
- src/features/indexing/utils.ts
This PR aims to add experimental support for music on SD cards. We currently can't test this as I don't have an Android device that supports one (hence why this is experimental). **We carry on the restriction that we'll look only for music files inside a `Music` folder on the "root" level** (mainly to prevent any potentially non-music audio that gets saved - ie: ringtones).
- This restriction will probably be lifted in the future once we implement some sort of "whitelist" feature.
In addition, this PR also:
- Fixed weird behavior w/ "back gesture" when on the `FOLDERS` tab in some scenarios.
- Add some animations to the breadcrumbs on the `FOLDERS` tab.
The first thing we needed to do is fix the stack behavior on the `FOLDERS` tab along with enabling displaying other external storage …
> feat: Experimental support for music on SD card

- src/features/indexing/api/index-audio.ts
- src/features/indexing/api/index-override/index.ts
- src/features/indexing/api/library-scan.ts
- src/features/indexing/hooks/useIndexAudio.ts
As mentioned in the previous pull request, I felt the generation of the paths that make up the "Folders" structure feature is kind of a bottleneck. Since we have to read & traverse through the directories on the user's device, the poor performance would really show when we add in the whitelist/blacklist feature as we'll end us scanning more directories (which may end up become all directories).
The solution I probably should have done originally is to generate the paths for the folder structure based on the uris of the tracks we've saved. This ends up being a way faster operation and finishes drastically faster compared to the recursive reading of directories.
In addition, to prepare for the whitelist/blacklist feature, we slightly modified the generation so now, instead of having say …
> chore: Speed up folder structure generation

- android/app/src/main/AndroidManifest.xml
When submitting the app to the Play Console, it typically runs a test suite against it. I noticed in the Sentry logs that we got this issue, but only for Android 12. I assumed it was to them not accepting permissions.
Then we got #62, which shown that this was in fact a real issue and seems to be affecting Android 12.
The issue stemmed from the `expo-media-library` package. In fact, I actually encountered this issue in the past when testing the app on my OnePlus 6 running Android 11. I was limiting the scope of the `WRITE_EXTERNAL_STORAGE` permission to only take effect up-to Android 10 as in [Android 11, the permission has not effect](https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE).
So the problem stems from me limiting the scope of the …
> fix: `Missing MEDIA_LIBRARY permissions.`

- src/app/_layout.tsx
- src/components/navigation/animated-boot-splash.tsx
- src/features/indexing/Config.ts
- src/features/indexing/api/index-override/index.ts
It seems like in Android 12+, `react-native-bootsplash`'s "autohide" behavior sometimes doesn't work as expected, causing the splash screen to persist when it shouldn't.
I've also fixed an issue where the Quick Start modal briefly appears with the splash screen.
This fixes #61.
To fix the Quick Start modal issue, I created a new migration that sets the variable that tracks whether you dismissed the modal to `false` and only display the modal when we see `false` (previously, we checked for `undefined` and the default value was `undefined` - even if the variable hasn't been asynchronously read).
To fix the issue with `react-native-bootsplash`, I added an addition `useEffect()` that runs whenever the navigation gets mounted (ie: we finish our loading logic & haven't seen any errors). …
> fix: Double Bootsplash

- src/app/setting/library.tsx
- src/features/setting/api/library-rescan.ts
This improves the "rescan" feature to now also look for any new tracks and save it into the database so it can be searched up in the app. This supplements for a potential future "auto rescan" feature (user can manually request a rescan instead of needing to relaunch the app).
Change the values in the allowlist & blocklist and then use the new rescan feature to see if it displays the expected tracks.
> chore: Improved rescan feature

- mobile/src/app/(main)/(home)/artist.tsx
- mobile/src/app/(main)/(home)/folder.tsx
- mobile/src/app/(main)/_layout.tsx
- mobile/src/app/search.tsx
- mobile/src/components/Typography/Kbd.tsx
- mobile/src/components/Typography/index.ts
- mobile/src/modules/search/components/SearchEngine.tsx
- mobile/src/modules/search/components/SearchResult.tsx
- mobile/src/modules/search/components/index.ts
- mobile/src/modules/search/hooks/useSearch.ts
- mobile/src/modules/search/types.ts
- mobile/src/queries/artist.ts
- mobile/src/screens/Sheets/ScanFilterList/index.tsx
- mobile/src/screens/Sheets/TrackToPlaylist.tsx
- mobile/src/screens/Sheets/TrackUpcoming.tsx
Add a basic search feature which returns albums, artists, playlists, and tracks through:
- Partial match (ie: the query matches part of the name).
- Partial album match for tracks (ie: the album on a track starts with the query).
> [!NOTE]  
> What we return from the specified query may change in the future based on behavior expected by users.
The press behavior of the results are as follows:
- Clicking on a track will play that track from "all tracks" (ie: same behavior as finding and playing a track on the Track screen).
- Clicking on an album, artist, or playlist will bring you to their respective pages.
One weird behavior when working on the `onPress` actions on the Search screen is that when we go "back" after doing a `navigate` action, we don't return to the Search screen. Using a …
> feat: Search Functionality

- mobile/src/api/album.ts
- mobile/src/app/current-track.tsx
- mobile/src/components/TopAppBar.tsx
- mobile/src/db/drizzle/0005_nappy_talon.sql
- mobile/src/db/drizzle/meta/0005_snapshot.json
- mobile/src/db/drizzle/meta/_journal.json
- mobile/src/db/drizzle/migrations.js
- mobile/src/db/schema.ts
- mobile/src/modules/scanning/constants.ts
- mobile/src/modules/scanning/helpers/artwork.ts
- mobile/src/modules/scanning/helpers/audio.ts
- mobile/src/modules/scanning/helpers/migrations.ts
- mobile/src/modules/scanning/helpers/rescan.ts
- mobile/src/queries/track.ts
- mobile/src/screens/Sheets/Track.tsx
- mobile/src/utils/number.ts
Satisfies one of the feature requests from way back and enables us to improve sorting within albums.
- Add metadata for disc number, bitrate, sample rate, format (file mimetype), and file size.
- Now sort tracks in albums by disc number then track number.
- Add new "stats" section in track modal, displaying additional information about the track such as bitrate, sample rate, size, etc.
- Known issue where `.flac` files don't have a bitrate assigned to it (will be revisiting our `@missingcore/react-native-metadata-retriever` package later).
- Fixed "bricking" that occurs due to encountering an Out of Memory error when saving artwork of tracks.
Ensure that our migrations to get the new metadata work.
> feat: Support additional track metadata

- docs/supported-gestures.md
- mobile/src/api/artist.ts
- mobile/src/api/playlist.ts
- mobile/src/api/track.ts
- mobile/src/app/(main)/(current)/artist/[id].tsx
- mobile/src/app/(main)/(home)/artist.tsx
- mobile/src/db/drizzle/0006_slow_deathstrike.sql
- mobile/src/db/drizzle/meta/0006_snapshot.json
- mobile/src/db/drizzle/meta/_journal.json
- mobile/src/db/drizzle/migrations.js
- mobile/src/db/schema.ts
- mobile/src/db/utils.ts
- mobile/src/layouts/CurrentList.tsx
- mobile/src/lib/file-system.ts
- mobile/src/modules/media/services/Playback.ts
- mobile/src/modules/scanning/helpers/artwork.ts
- mobile/src/modules/search/components/SearchEngine.tsx
- mobile/src/queries/album.ts
- mobile/src/queries/artist.ts
- mobile/src/queries/playlist.ts
- mobile/src/screens/Sheets/Artwork.tsx
- mobile/src/screens/Sheets/index.ts
- mobile/src/utils/string.ts
- Support artwork for artists.
- Updated how we define extra configs in schema (use array instead of object as object method is deprecated).
- Create sheet for changing artwork for artist & playlists by long-pressing on that image on their respective screens.
- Add documentation for long-press gesture.
> feat: Artwork sheet & support artist artwork

- mobile/src/api/playlist.ts
- mobile/src/app/(main)/(current)/_layout.tsx
- mobile/src/app/(main)/(current)/playlist/[id].tsx
- mobile/src/app/(main)/(current)/playlist/modify.tsx
- mobile/src/modules/media/services/Music.ts
- mobile/src/modules/media/services/Playback.ts
- mobile/src/modules/media/services/Resynchronize.ts
- mobile/src/queries/playlist.ts
- mobile/src/screens/ModifyPlaylist.tsx
With this PR, we'll reach "feature parity" with what we have prior as we've previously removed the logic for creating, editing, and deleting playlists (which the features have been re-added with recent PRs).
**Other Changes:**
- Fixed issue where our playback logic didn't properly handle the case when we're playing a list with no tracks remaining (as we couldn't really simulate this behavior prior).
> [!NOTE]  
> We initially want to add some sort of animation with the delete sequence, but that's a bit extra and it works without it (plus I want to get this update out as soon as possible).
>
> We've also tested to see if anything would get cut off if we disabled the Android navigation bar and everything seemed fine enough (this mainly depends on the radius of the screen, which is different …
> chore: Re-add ability to edit & delete playlists

- mobile/src/icons/RepeatOne.tsx
- mobile/src/icons/index.ts
- mobile/src/modules/i18n/CHANGELOG.md
- mobile/src/modules/i18n/translations/en.json
- mobile/src/modules/media/components/MediaControls.tsx
- mobile/src/modules/media/services/Music.ts
- mobile/src/modules/media/services/Playback.ts
- mobile/src/screens/Sheets/TrackUpcoming.tsx
- mobile/src/services/RNTPService.ts
This enables the ability to repeat the current playing track.
- Created custom SVG to represent the "Repeat One" button based on ionicon's "Repeat" and "Calendar Number" icons (sharp variants).
- We've added a `common.repeatOne` translation key that's used for the accessibility label for the button.
The functionality is what I've briefly observed with Spotify's implementation:
> feat: Add "Repeat One" mode

- mobile/src/modules/scanning/helpers/artwork.ts
- mobile/src/modules/scanning/helpers/audio.ts
- mobile/src/modules/scanning/helpers/rescan.ts
- mobile/src/utils/promise.ts
Around a week ago, we applied some SQL optimizations to the import feature where we did bulk insertion of values instead of inserting an entry one-by-one in a loop. From that experiment, we saw a decent improvement in the time it takes from reading the file to the saving those values in the database (we went from ~2.7s to ~1.3s). One of the places this idea can also be applied to is the indexing logic, or the logic which is run to find and save the metadata of the various tracks found on the device.
Some observations from applying these optimizations include:
- A ~2.4s reduction (~9.6s to ~7.2s) in the time it takes to save the 25 artwork/covers found from the 238 tracks available in **development** mode.
- We saw no impactful improvement from optimization tests for the main indexing …
> perf: Optimized SQL queries for indexing logic

- THIRD_PARTY.md
- mobile/android/app/src/main/res/values-night/colors.xml
- mobile/android/app/src/main/res/values/colors.xml
- mobile/android/app/src/main/res/values/styles.xml
- mobile/app.config.ts
- mobile/package.json
- mobile/pnpm-lock.yaml
- mobile/src/app/setting/third-party/[id].tsx
- mobile/src/app/setting/update.tsx
- mobile/src/components/Sheet.tsx
- mobile/src/layouts/Issue.tsx
- mobile/src/layouts/StandardScroll.tsx
- mobile/src/modules/i18n/translations/zh-Hans.json
- mobile/src/providers/ThemeProvider.tsx
- mobile/src/providers/index.tsx
- mobile/src/resources/licenses.json
- Integrated react-native-edge-to-edge to enable edge-to-edge layout, ensuring a fully immersive experience
- Refined and optimized some Simplified Chinese translations for better clarity and consistency
<table>
<tr>
<td><strong>Before</strong></td>
<td><strong>After</strong></td>
</tr>
<tr>
<td>
</td>
<td>
</tr>
</table>
> feat: Add edge-to-edge support for dark mode navigation bar

- mobile/src/app/_layout.tsx
- mobile/src/app/current-track.tsx
- mobile/src/app/now-playing.tsx
- mobile/src/hooks/useBottomActionsContext.ts
- mobile/src/layouts/CurrentList.tsx
- mobile/src/modules/media/components/MediaImage.tsx
- mobile/src/modules/media/components/MiniPlayer.tsx
- mobile/src/modules/media/components/Vinyl.tsx
- mobile/src/modules/search/components/SearchResult.tsx
- mobile/src/providers/RouteHandlers.tsx
- mobile/src/screens/NowPlaying/SeekService.ts
- mobile/src/screens/NowPlaying/useVinylSeekbar.ts
- mobile/src/screens/Sheets/Artwork.tsx
- mobile/src/screens/Sheets/Track.tsx
Created a new vinyl design to replace the old design that was temporarily removed in the v2 redesign. This design is more symmetrical (just a disk instead of sleeve + disk) and will look more consistent across devices.
- A full revolution of the vinyl is `24s` long.
- Re-created the sleeve + disk animation for the albums & playlists screen. Instead of the vinyl moving to the right, the sleeve moves to the left (as we want as much space as possible for the metadata that's on its right).
- The vinyl on the "Now Playing" screen now spins proportionally to the seek bar position. In addition, it syncs with when we drag the thumb in the seek bar (ie: spins back and forwards).
- Slight adjustment to `<MediaImage />`.
- Renamed `/current-track` route to `/now-playing`.
> feat: Updated vinyl design (Part 1)

- docs/supported-gestures.md
- mobile/src/app/now-playing.tsx
- mobile/src/screens/NowPlaying/useVinylSeekbar.ts
The PR adds the ability to use the vinyl on the "Now Playing" screen as a seekbar. As mentioned in the previous PR, a full revolution is equivalent to `24s`.
- We included logic to prevent over rotating the vinyl beyond its duration.
I initially wanted to use the [Rotation Gesture](https://docs.swmansion.com/react-native-gesture-handler/docs/gestures/rotation-gesture/) from `react-native-gesture-handler`, but it required using 2 fingers to activate the tracking and it wasn't that accurate.
> feat: Updated vinyl design (Part 2)

- mobile/package.json
- mobile/pnpm-lock.yaml
- mobile/src/app/(main)/(current)/playlist/[id].tsx
- mobile/src/app/setting/appearance/home-tabs-order.tsx
- mobile/src/components/Defaults.tsx
- mobile/src/lib/react-native-draglist.ts
- mobile/src/resources/licenses.json
- mobile/src/screens/ModifyPlaylist/index.tsx
- mobile/tsconfig.json
- Updated `react-native-draglist` package to export FlashList variant in its own file, allowing us to use the initial FlatList variant.
- Dedupe code for localized async state (which prevents content flashing from its old position to new) and memoization comparison function for rendering the draglist items.
- Some what fixed issue where the long-press behavior doesn't trigger due to `onPressOut` firing before the `onLongPress` event for whatever reason.
- We replaced `onLongPress` with `onPressIn`, which fixed the issue, but only for the home tabs reordering screen as using `onPressIn` instead of `onLongPress` for the other uses would break the swipeable behavior.
> chore: Drag list improvements

- mobile/src/app/(main)/(home)/_layout.tsx
- mobile/src/app/(main)/_layout.tsx
- mobile/src/app/now-playing.tsx
- mobile/src/app/setting/appearance/home-tabs-order.tsx
- mobile/src/icons/Eye.tsx
- mobile/src/icons/EyeOff.tsx
- mobile/src/services/UserPreferences.ts
This PR adds the ability to hide tabs. Though a problem with the current set up is that **it's impossible to make the hidden route accessible under a different navigator**. This is important as it prevents any unexpected behavior caused by the route being disabled. From exploring information about `expo-router`, the idea that I have (ie: conditionally rendering routes to ignore file-based routing) doesn't work, so we need to explore potentially switching everything over to `react-navigation`.
The idea I had was:
```
- (home)
- index
- folder
- playlist
- track
- album
- artist
- (hidden)
- folder
- playlist
- track
- album
- artist
```
If we hide the "album" & "artist" route, we want to conditionally render those routes under the "(hidden)" group, which uses a different navigator (to …
> feat: Tab visibility (Part 1)

- mobile/src/app/(main)/(current)/artist/[id].tsx
- mobile/src/db/drizzle/0006_wild_gabe_jones.sql
- mobile/src/db/drizzle/meta/0006_snapshot.json
- mobile/src/db/drizzle/meta/_journal.json
- mobile/src/db/drizzle/migrations.js
- mobile/src/db/schema.ts
- mobile/src/db/utils.ts
- mobile/src/modules/scanning/constants.ts
- mobile/src/modules/scanning/helpers/_album-fracturization.ts
- mobile/src/modules/scanning/helpers/audio.ts
- mobile/src/modules/scanning/helpers/migrations.ts
- mobile/src/utils/number.ts
- mobile/src/utils/string.ts
In SQL, it's considered a pretty bad idea to have a column with `null` as a potential value be part of a unique key as `null != null`. Some references:
- https://stackoverflow.com/a/43828095
- https://stackoverflow.com/a/22699498
In our case, an issue arises because we do use a column with potentially `null` values for the Album unique key (in the form of the `releaseYear` column). This would then cause the duplicate album behavior to occur. This never got caught by me as all my tracks are properly tagged, so I never encountered the issue where I had an album with no associated release year.
This fixes the original issue in #160.
In addition, we trim important information such as track name, album name, artist name, and album artist name in the situation where there's extra spaces on …
> fix: Duplicate albums caused by album not having an associated year

- mobile/src/api/playlist.ts
- mobile/src/api/track.ts
- mobile/src/db/slimTypes.ts
- mobile/src/db/utils.ts
- mobile/src/modules/search/components/SearchEngine.tsx
- mobile/src/modules/search/hooks/useSearch.ts
- mobile/src/modules/search/types.ts
- mobile/src/queries/playlist.ts
- mobile/src/screens/ModifyPlaylist/context.tsx
- mobile/src/screens/ModifyPlaylist/index.tsx
Similar to the issue with launch performance tanking due to returning more data than necessary, this issue also occurs when opening the search modal for tracks while on the create/modify playlists screen. This is because we fetch all types of media data (albums, artists, playlists, and tracks) without slimming it down.
Essentially, what's happening is that fetching the data is blocking the modal appear animation from running until that task is done. This issue doesn't occur on the "Search" screen.
> perf: Improve search modal open speed for users with lots of tracks

- mobile/src/modules/media/helpers/data.ts
- mobile/src/modules/media/services/Music.ts
- mobile/src/modules/media/services/Playback.ts
- mobile/src/modules/media/services/_subscriptions.ts
- mobile/src/providers/index.tsx
- mobile/src/screens/Sheets/TrackUpcoming.tsx
- mobile/src/screens/Sheets/TrackUpcoming/context.tsx
- mobile/src/screens/Sheets/TrackUpcoming/index.tsx
- mobile/src/services/RNTPService.ts
One of the potential areas that I mentioned I wanted to improve on in #155 for performance was the changing the store that tracks the list of tracks we want to play. As it stands current, we load all the tracks in the list we're currently playing, which might become an issue if we have thousands of tracks and are currently playing "All Tracks".
This also gives us the opportunity to fix some other issues caught by Sentry, most noticeably, an issue where `getTracksFromIds()` returns `undefined` for some reason, which gets consumed somewhere in `Music.ts` (ie: a subscription) and breaks things.
What this PR does is:
- Address some of the issues caught by Sentry.
- Lean into referencing the list of track ids instead of the list of Track objects for logic in `Music.ts`.
This is mainly …
> chore: Restructure "Music" store & fix some flakey code

- mobile/src/app/_layout.tsx
- mobile/src/app/now-playing.tsx
- mobile/src/components/Containment/SafeContainer.tsx
- mobile/src/components/TopAppBar.tsx
- mobile/src/screens/NowPlaying/Artwork.tsx
- mobile/src/services/UserPreferences.ts
I've received a request a while back asking for whether we'll reintroduced the "old" vinyl design, which became feasible as after I sent `v2.1.0` for review, I just realized that I could copied the idea used for the "current" screens and have the cover move off-screen. This makes calculating the area easier as all we care about is getting a square instead of a rectangle (since prior, the vinyl moved), which also keeps the more "consistent" design across devices.
A quick summary of the design:
- We use the new vinyl design & logic instead of the original look (which was the one from the Nothing Recorder app), meaning we get the benefits of the new design (using it as a seekbar).
- The cover can go under the header.
- This looks good in dark mode, but bad in light mode due to wanting to …
> chore: Option to use "old" v1 vinyl design on the "Now Playing" screen

- mobile/src/app/_layout.tsx
- mobile/src/app/now-playing.tsx
- mobile/src/components/Containment/Marquee.tsx
- mobile/src/components/Form/Slider.tsx
- mobile/src/components/TopAppBar.tsx
- mobile/src/icons/KeyboardArrowDown.tsx
- mobile/src/screens/NowPlaying/Artwork.tsx
- mobile/src/screens/NowPlaying/TopAppBar.tsx
This PR modifies the "Now Playing" screen to:
- Support for going directly to the current list being played by clicking the "Playing From" at the top.
- Folders are not supported as of now.
- Improve one-hand usability by moving buttons down.
- Improve the design when using the `Vinyl (Legacy)` artwork design.
- Moves the back button to the bottom left corner and hides the "Playing From" text.
- Support for going directly to the track's album or artist page by clicking on the displayed album or artist name.
> chore: Modified "Now Playing" design

- mobile/src/api/utils.ts
- mobile/src/db/drizzle/0007_cooing_the_stranger.sql
- mobile/src/db/drizzle/meta/0007_snapshot.json
- mobile/src/db/drizzle/meta/_journal.json
- mobile/src/db/drizzle/migrations.js
- mobile/src/db/schema.ts
- mobile/src/db/slimTypes.ts
- mobile/src/db/utils.ts
- mobile/src/layouts/CurrentList.tsx
- mobile/src/modules/media/services/RecentList.ts
- mobile/src/modules/scanning/helpers/artwork.ts
- mobile/src/modules/search/components/SearchEngine.tsx
- mobile/src/modules/search/hooks/useSearch.ts
- mobile/src/queries/album.ts
- mobile/src/queries/keyStore.ts
- mobile/src/screens/ModifyPlaylist/context.tsx
- mobile/src/screens/Sheets/Artwork.tsx
- mobile/src/screens/Sheets/TrackUpcoming/store.ts
- mobile/src/screens/Sheets/index.ts
This adds support for "overriding" the artwork used for an album (the original found artwork will still be saved on the device; just the overriding artwork being displayed). This uses the same UI as when changing the artwork for artists & playlists.
Do note that:
- The artwork for the "active track" won't change immediately if that album's artwork gets changed.
- The artwork of the tracks in the "Upcoming" modal won't change if any of the albums those tracks belong to change (since the values are cached from when we first opened the modal).
> feat: Support for "overriding" album artwork

- mobile/src/app/(main)/(current)/artist/[id].tsx
- mobile/src/app/(main)/(current)/playlist/Favorite Tracks.tsx
- mobile/src/app/(main)/(current)/playlist/[id].tsx
- mobile/src/app/(main)/(home)/album.tsx
- mobile/src/app/(main)/(home)/artist.tsx
- mobile/src/app/(main)/(home)/folder.tsx
- mobile/src/app/(main)/(home)/index.tsx
- mobile/src/app/(main)/(home)/playlist.tsx
- mobile/src/app/(main)/(home)/track.tsx
- mobile/src/app/(main)/_layout.tsx
- mobile/src/app/setting/insights/save-errors.tsx
- mobile/src/app/setting/third-party/index.tsx
- mobile/src/components/Containment/List.tsx
- mobile/src/components/Defaults.tsx
- mobile/src/components/Transition/Placeholder.tsx
- mobile/src/layouts/Issue.tsx
- mobile/src/layouts/StickyActionScroll.tsx
- mobile/src/modules/media/components/MediaCard.tsx
- mobile/src/modules/media/components/Track.tsx
- mobile/src/modules/search/components/SearchEngine.tsx
- mobile/src/queries/artist.ts
- mobile/src/screens/ModifyPlaylist/index.tsx
- mobile/src/screens/Sheets/ScanFilterList/index.tsx
- mobile/src/screens/Sheets/TrackToPlaylist.tsx
- mobile/src/screens/Sheets/TrackUpcoming/index.tsx
This PR applies the changes in how we render data in lists (using "preset hooks" instead of full-blown components), cherry-picked from #221.
- Ensure that the app visually looks and feel the same as if we haven't made these changes.
> refactor: Rendering data in lists

- mobile/src/app/(main)/(current)/album/[id].tsx
- mobile/src/app/(main)/(current)/artist/[id].tsx
- mobile/src/app/(main)/(current)/playlist/Favorite Tracks.tsx
- mobile/src/app/(main)/(home)/artist.tsx
- mobile/src/app/(main)/(home)/folder.tsx
- mobile/src/app/(main)/(home)/index.tsx
- mobile/src/app/(main)/_layout.tsx
- mobile/src/app/setting/appearance/home-tabs-order.tsx
- mobile/src/app/setting/insights/save-errors.tsx
- mobile/src/app/setting/third-party/index.tsx
- mobile/src/components/Defaults.tsx
- mobile/src/layouts/StickyActionScroll.tsx
- mobile/src/modules/search/components/SearchEngine.tsx
- mobile/src/screens/NowPlaying/Sheets.tsx
- mobile/src/screens/Sheets/Settings/Root.tsx
- mobile/src/utils/validation.ts
This PR applies some optimizations to the existing lists since we narrowed down the performance issue w/ navigation to "Current Album/Artist" screens with lots of tracks to Legend List.
- Fixed horizontal padding not working when passed in `contentContainerClassName` (due to FlashList internally extracting `contentContainerStyle` and applying it to a internal component - explictly remapping the prop fixes the issue).
- Utilize `getItemType` to tell FlashList to use separate recycling pool when we render different types of components in the list.
- All list components used should be from `Defaults.tsx`.
- Replaced use of `SheetsFlatList` with `SheetsFlashList` (we need to use the `snapTop` prop as otherwise, the FlashList won't have a defined height).
- Created new `AnimatedFlashList` …
> refactor: List optimizations

- mobile/src/modules/i18n/translations/pl.json
- Added missing translations added in v2.3.0
- Fixed plural translations (used appropriate suffixes)
> i18n: Polish translation update

- mobile/src/components/Defaults.tsx
- mobile/src/components/Sheet.tsx
- mobile/src/screens/Sheets/Settings/Root.tsx
- mobile/src/screens/Sheets/Track.tsx
There's a "rare" situation where gestures directly on the sheet (to expand or dismiss) doesn't work. This was narrowed down to having a scrollable container inside the sheet with the `nestedScrollEnabled` prop, where the sheet doesn't take up the whole screen. Disabling `nestedScrollEnabled` (when it's not even needed) fixed the issue.
This was solved by creating a `useIsScrollable` hook in the `Defaults.tsx` file (where we export all the scrollable components) that return event handlers and a boolean on whether the scrollable can be scrolled.
<div id='description'>
<a href="https://bito.ai#summarystart"></a>
<h3>Summary by Bito</h3>
This PR fixes a rare issue with sheet gestures in nested scrollable containers by implementing the useIsScrollable hook. The hook intelligently determines …
> fix: Sheet gesture not working with scrollable child with `nestedScrollEnabled`

- mobile/src/api/artist.ts
- mobile/src/app/(main)/(current)/artist/[id].tsx
- mobile/src/db/drizzle/0010_brief_exodus.sql
- mobile/src/db/drizzle/meta/0010_snapshot.json
- mobile/src/db/drizzle/meta/_journal.json
- mobile/src/db/drizzle/migrations.js
- mobile/src/db/schema.ts
- mobile/src/db/utils.ts
- mobile/src/modules/scanning/constants.ts
- mobile/src/modules/scanning/helpers/audio.ts
- mobile/src/modules/scanning/helpers/migrations.ts
- mobile/src/screens/ModifyTrack/context.tsx
- mobile/src/utils/number.ts
This is a more "permanent" fix to the problem of duplicate albums caused by having different release years (see #220). This "deprecates" the use of `releaseYear` as part of what makes an `Album` entry unique.
- We have a new `year` field in the `Track` schema.
- Created a migration that copies over the `releaseYear` to the `year` field, then merges all the albums with the same name & artist.
- We set `releaseYear = -1` as we can't necessarily remove this field yet (alongside the unique constraint as otherwise, the app would crash for users with duplicate albums).
- Fixed how we display the album release year on the album screen and in the list of albums in the artist screen.
> [!NOTE]
> We plan on deprecating the `releaseYear` Album field alongside its use as part of the unique constraint …
> fix: Duplicate Albums From Different Release Years

- mobile/src/modules/media/helpers/revalidate.ts
- mobile/src/modules/scanning/helpers/artwork.ts
- mobile/src/screens/ModifyTrack/context.tsx
- Create reusable function for saving the embedded track artwork, which can be used during the onboarding process and when we're editing track metadata.
- Fix issue where we edit the track metadata before the RNTP service has been "activated" due to `TrackPlayer.getActiveTrack()` throwing an error. This would result in `activeTrack` not getting updated as.
<div id='description'>
<a href="https://bito.ai#summarystart"></a>
<h3>Summary by Bito</h3>
This PR refactors artwork processing and track metadata updating to improve reliability and reusability. It adds validation for active tracks before metadata updates and creates a dedicated function for artwork handling. These changes enhance error handling and improve code maintainability across modules.
</div>
> refactor: Make saving embedded artwork more reusable

- mobile/src/db/drizzle/0011_mute_eternity.sql
- mobile/src/db/drizzle/meta/0011_snapshot.json
- mobile/src/db/drizzle/meta/_journal.json
- mobile/src/db/drizzle/migrations.js
- mobile/src/db/schema.ts
- mobile/src/modules/i18n/translations/en.json
- mobile/src/modules/media/services/SortPreferences.ts
- mobile/src/modules/scanning/constants.ts
- mobile/src/modules/scanning/helpers/audio.ts
- mobile/src/modules/scanning/helpers/migrations.ts
- mobile/src/queries/keyStore.ts
This PR adds a new sort option for "Discover Time". This will be the time that the track was discovered and saved into the app's database.
For pre-existing tracks where we didn't save the "Discover Time" information, we'll instead use their `modificationTime` value.
> feat: Add "Discover Time" sort option

- mobile/src/modules/scanning/helpers/audio.ts
- mobile/src/modules/scanning/helpers/folder.ts
- mobile/src/modules/scanning/helpers/migrations.ts
- mobile/src/modules/scanning/helpers/rescan.ts
This PR rewrites `savePathComponents()` to allow passing an array of URIs, which drastically reduced the time it takes to regenerate the folder structure for the files we track.
- We no longer pre-check to see if the URI was already saved and instead, just save everything as this would probably add a bit of delay as we then need to read the DB for these values.
For 4987 tracks, regenerating the folder structure via the rescan feature:
- The old method took `23.0450s`.
- The refactored method took `0.1423s`.
This does give us hope for improving the performance of onboarding by using bulk insertion.
> [!NOTE]
> One thing we need to keep in mind is that we don't want to bulk insert too many entries as otherwise, Drizzle will throw an `RangeError: Maximum call stack size exceeded (native …
> refactor: Improve performance of `savePathComponents()`

- mobile/package.json
- mobile/pnpm-lock.yaml
- mobile/src/modules/scanning/helpers/artwork.ts
- mobile/src/modules/scanning/helpers/audio.ts
- mobile/src/resources/licenses.json
This PR updates our code to use the latest features from our `@missingcore/react-native-metadata-retriever` package that we currently have in beta.
- The reusable `getArtworkUri` function now uses the new `saveArtwork` function instead of `getArtwork` + `saveImage`.
- Using `getBulkMetadata` instead of `getMetadata` actually increases the onboarding time, so we're sticking with the old method.
- The problem seems to be trying to get the file size of 50 tracks synchronously at the same time.
> chore: Use latest metadata retriever API

- mobile/patches/@react-native-assets__slider.patch
- mobile/pnpm-lock.yaml
- mobile/src/app/(main)/(current)/artist/[id].tsx
- mobile/src/app/(main)/(current)/playlist/[id].tsx
- mobile/src/app/(main)/(current)/recently-played.tsx
- mobile/src/app/(main)/(home)/folder.tsx
- mobile/src/app/(main)/_layout.tsx
- mobile/src/app/setting/update.tsx
- mobile/src/components/Containment/Marquee.tsx
- mobile/src/components/Form/Input.tsx
- mobile/src/components/Form/Slider.tsx
- mobile/src/components/Form/Switch.tsx
- mobile/src/components/TopAppBar.tsx
- mobile/src/components/Typography/AccentText.tsx
- mobile/src/components/Typography/StyledText.tsx
- mobile/src/layouts/CurrentList.tsx
- mobile/src/lib/react.tsx
- mobile/src/modules/media/components/MediaCard.tsx
- mobile/src/modules/media/components/Vinyl.tsx
- mobile/src/screens/ModifyPlaylist/index.tsx
- mobile/src/screens/NowPlaying/Sheets.tsx
- mobile/src/screens/NowPlaying/TopAppBar.tsx
- mobile/src/screens/Sheets/Settings/Appearance.tsx
- mobile/src/screens/Sheets/Settings/Scanning.tsx
- mobile/src/services/UserPreferences.ts
This PR adds improved support for RTL layouts, which was broken in a sense since it was enabled in `v2.3.0`? If the device language is RTL, then the app UI would be automatically updated to reflect it.
- This really only got noticed when testing the Arabic translations after an app relaunch.
How we now handle RTL is as follows:
- If a RTL language is selected in the app from an LTR language, the layout will be adjusted to RTL on **next app relaunch**.
- If a LTR language is selected in the app from an RTL language, the layout will be adjusted to LTR on **next app relaunch**.
- Essentially, we'll ignore the device language for determine whether a RTL layout will be used.
**Some Notes:**
- RTL layout ended up breaking a lot of things, most notably animations (ie: Marquee), animated …
> feat: Improved RTL Support

- mobile/android/app/src/main/AndroidManifest.xml
- mobile/app.config.ts
- mobile/src/app/+native-intent.tsx
- mobile/src/app/notification.click.tsx
This PR adds support for opening an audio file with this app when we select "Open With".
Handling playback from doing an "Open With" isn't straight forwards as it's treated like a deep link in React Native & `expo-router`. `expo-router` handles deep-linking (what the "Open With" does) via the routes, which is annoying. However, there's a [special `+native-intent.tsx` file](https://docs.expo.dev/router/advanced/native-intent/) that we can use to intercept these deep links and rewrite the path.
- This allows us to remove the `notification.click.tsx` route as it was added due to potentially the media notification staying when we closed the app, and when we click on it, we would encounter the "Now Found" route.
From some investigation, the uris returned from the deep link can vary - it could …
> feat: Update `AndroidManifest.xml` intent filters to support "Open With" on audio files

- mobile/index.ts
- mobile/package.json
- mobile/src/services/RNTPService.ts
We had a weird issue that I've recently noticed which is when the next track naturally plays:
- We hear the next track start twice.
- The track plays for a frame, then immediately pauses.
- This only happens in a specific situation (open the app to the current track not starting at 0s, then letting it naturally play the next track).
`v2.5.2` never had this issue, so it was introduced somewhere in the `next` branch. We ended up narrowing down to the 1st commit to the branch, which is the switch over the React Navigation.
The overall cause in the end was that the `PlaybackService` ended up being registered twice. For some reason, this never happened when using `expo-router`.
- I guess the `setupPlayer()` in the entry file & `useSetup()` hook both managed to set up the RNTP service, causing …
> fix: Scuffed playback when next track naturally plays

- docs/supported-gestures.md
- mobile/src/components/BounceSwipe.tsx
- mobile/src/components/BounceSwipeable.tsx
- mobile/src/modules/i18n/translations/en.json
- mobile/src/navigation/components/MiniPlayer.tsx
- mobile/src/navigation/screens/settings/AppearanceSettingsView/index.tsx
- mobile/src/resources/icons/NothingArrowRight.tsx
- mobile/src/services/UserPreferences.ts
This PR adds the ability to replace the next/prev buttons on the miniplayer with a swipe gesture on the text-portion of the miniplayer (by default, this is turned off).
- Can be changed via `Miniplayer Gestures` setting in `Settings > Appearance` screen.
You may not be able to swipe again immediately if we switch to a track with large-sized artwork attached.
- Remove press-styling on miniplayer as it triggers when we start the swipe gesture, which is annoying.
- New `BounceSwipeable` component which is like `Swipeable`, but activates the action on the swipe.
> feat: Swipe gestures on miniplayer
